---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/mwalburn/pcf-ers-demo.git
    branch: master

- name: pws-dev
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: mwalburn@pivotal.io
    password: pwsm4dr)(gl
    organization: mwalburn
    space: development
    skip_cert_check: true

jobs:
- name: build-ers-demo-dev
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/ci/build.yml
  - put: pws-dev
    params:
      manifest: source-code/manifest.yml
      path: build-output/pcf-ers-demo1-0.0.1-SNAPSHOT.jar
